# Generated by Django 3.0.8 on 2020-07-31 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=35)),
                ('slug', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Body', models.TextField()),
                ('Date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slug', models.SlugField()),
                ('Author_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Claps', models.ManyToManyField(null=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('Tags', models.ManyToManyField(to='BlogPost.Tag')),
            ],
        ),
    ]
