# Generated by Django 3.0.8 on 2020-07-31 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogPost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='Claps',
        ),
        migrations.AddField(
            model_name='posts',
            name='claps',
            field=models.ManyToManyField(blank=True, related_name='claps', to=settings.AUTH_USER_MODEL),
        ),
    ]
